// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3HuF8tAg9Tukp2BwG9JNceiK2AAAh7xw',
    appId: '1:667697448675:web:79733b50de24e0ef2da7d6',
    messagingSenderId: '667697448675',
    projectId: 'calories-counter-8b76c',
    authDomain: 'calories-counter-8b76c.firebaseapp.com',
    storageBucket: 'calories-counter-8b76c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvmHRgr0XQQnIf1CrsemuRfn5Xg-dpTU0',
    appId: '1:667697448675:android:ef334458dee76c2c2da7d6',
    messagingSenderId: '667697448675',
    projectId: 'calories-counter-8b76c',
    storageBucket: 'calories-counter-8b76c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW1hgpakK4KsP0GASvvnGGHMLntwLWrUI',
    appId: '1:667697448675:ios:a6ad7504a6b663372da7d6',
    messagingSenderId: '667697448675',
    projectId: 'calories-counter-8b76c',
    storageBucket: 'calories-counter-8b76c.appspot.com',
    iosBundleId: 'com.example.caloriesCounter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW1hgpakK4KsP0GASvvnGGHMLntwLWrUI',
    appId: '1:667697448675:ios:a6ad7504a6b663372da7d6',
    messagingSenderId: '667697448675',
    projectId: 'calories-counter-8b76c',
    storageBucket: 'calories-counter-8b76c.appspot.com',
    iosBundleId: 'com.example.caloriesCounter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3HuF8tAg9Tukp2BwG9JNceiK2AAAh7xw',
    appId: '1:667697448675:web:9fd854b60273201d2da7d6',
    messagingSenderId: '667697448675',
    projectId: 'calories-counter-8b76c',
    authDomain: 'calories-counter-8b76c.firebaseapp.com',
    storageBucket: 'calories-counter-8b76c.appspot.com',
  );
}
